# Taps
tap "derailed/k9s"
tap "grafana/grafana"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "nicoverbruggen/cask"
tap "norwoodj/tap"
tap "pulumi/tap"
tap "shihanng/tfvar"
tap "stripe/stripe-cli"
tap "stripe/stripe-mock"

# Binaries
brew "act"
brew "alloy"              # Grafana Alloy (grafana/grafana tap)
brew "aom"
brew "awscli"
brew "azure-cli"
brew "bash"               # Latest Bash version
brew "bash-completion"
brew "bat"                # Used for spatie/visit
brew "brew-cask-completion"
brew "cffi"
brew "coreutils"          # Those that come with macOS are outdated
brew "cri-tools"
brew "cryptography"
brew "docker-compose"
brew "docutils"
brew "etcd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "gimme-aws-creds"
brew "git"
brew "glib"
brew "gnutls"
brew "go"
brew "golang-migrate"
brew "grep"
brew "harfbuzz"
brew "helm"
brew "httpie"
brew "infracost"
brew "iproute2mac"
brew "jpeg-xl"
brew "jq"                 # Used for spatie/visit
brew "k6"                 # Load testing tool
brew "k8sgpt"
brew "kind"
brew "kubernetes-cli"
brew "kubectx"
brew "leptonica"
brew "lima"
brew "libass"
brew "libmicrohttpd"
brew "librist"
brew "localstack"
brew "mackup"
brew "mas"                # Mac App Store manager
brew "minikube"
brew "neovim"
brew "node"
brew "openjdk"
brew "openjpeg"
brew "opentofu"
brew "pipx"
brew "pkgconf"            # pkg-config replacement (homebrew renamed pkg-config → pkgconf)
brew "pycparser"
brew "pyenv"              # Used for switching Python versions
brew "python@3.11"
brew "redis"
brew "ripgrep"
brew "shellcheck"
brew "sonobuoy"
brew "stripe"             # Stripe CLI (stripe/stripe-cli tap)
brew "stripe-mock"        # Stripe mock server (stripe/stripe-mock tap)
brew "subversion"
brew "tesseract"
brew "terraform"
brew "terraform-docs"
brew "terraform-ls"
brew "terragrunt"
brew "tfenv"
brew "tflint"
brew "tmux"
brew "trivy"
brew "uv"
brew "webp"
brew "yarn"
brew "zsh"
brew "zsh-completions"

# Additional / SRE formulae (alphabetical)
brew "eksctl"             # EKS cluster management CLI
brew "flux"               # GitOps tool for Kubernetes (fluxcd/tap)
brew "helm-docs"          # Auto-generate Helm chart docs (norwoodj/tap)
brew "k9s"                # Kubernetes TUI (derailed/k9s tap)
brew "kustomize"          # Kubernetes manifest customization
brew "loki"               # Installs logcli for LogQL queries
brew "prometheus"         # Installs promtool for config/rule validation
brew "pulumi"             # Infrastructure as code (pulumi/tap)
brew "stern"              # Multi-pod log tailing for Kubernetes
brew "tfvar"              # Terraform variable file generator (shihanng/tap)
brew "yq"                 # YAML/JSON processor (like jq for YAML)
# DataDog agent → install via: https://docs.datadoghq.com/agent/basic_agent_usage/osx/

# Mac App Store
mas "Byword", id: 420212497
mas "GCalendar for Google Calendar", id: 1596768976
mas "Giphy Capture", id: 668208984
mas "iStatistica", id: 1025822138
mas "Keynote", id: 409183694
mas "Microsoft Outlook", id: 985367838
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "NordVPN", id: 905953485
mas "Numbers", id: 409203825
mas "Parallels Desktop", id: 1085114709
mas "PDF Reader Pro Lite", id: 919472673
mas "Slack", id: 803453959
mas "Speedtest", id: 1153157709
mas "Spring", id: 1508706541
mas "Telegram", id: 747648890
mas "Things", id: 904280696
mas "Trello", id: 1278508951
mas "WhatsApp", id: 1147396723

# VSCode / Cursor Extensions
# Note: anysphere.cursorpyright replaces ms-python.vscode-pylance in Cursor
vscode "4bde9604-932c-638d-b5d2-db273992f59c.python-silver-pack"
vscode "4ops.terraform"
vscode "aaron-bond.better-comments"
vscode "afpro.tfcomplete"
vscode "aldijav.golangwithdidi"
vscode "alefragnani.project-manager"
vscode "almenon.arepl"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "anysphere.cursorpyright"      # Cursor-native Pylance replacement
vscode "aooiu.markdown2confluence"
vscode "azapi-vscode.azapi"
vscode "azps-tools.azps-tools"
vscode "bar.python-import-helper"
vscode "batisteo.vscode-django"
vscode "betajob.modulestf"
vscode "bierner.markdown-emoji"
vscode "bierner.markdown-preview-github-styles"
vscode "caarlos0.language-prometheus"
vscode "casualjim.gotemplate"
vscode "charliermarsh.ruff"
vscode "codezombiech.gitignore"
vscode "cooper.ssh-terminal"
vscode "cstrap.python-snippets"
vscode "d-v-vislobokov.helmhelper"
vscode "davidanson.vscode-markdownlint"
vscode "deerawan.vscode-dash"
vscode "demystifying-javascript.python-extensions-pack"
vscode "denco.confluence-markup"
vscode "dongli.python-preview"
vscode "donjayamanne.git-extension-pack"
vscode "donjayamanne.githistory"
vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "eamodio.gitlens"
vscode "equinusocio.vsc-material-theme-icons"
vscode "erd0s.terraform-autocomplete"
vscode "formulahendry.code-runner"
vscode "foxundermoon.shell-format"
vscode "ginfuru.ginfuru-vscode-jekyll-syntax"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "grafana.grafana-alloy"        # Alloy config language support
vscode "grafana.grafana-vscode"       # Grafana dashboards in editor
vscode "grafana.vscode-jsonnet"
vscode "graykode.ai-docstring"
vscode "hashicorp.terraform"
vscode "hbenl.vscode-test-explorer"
vscode "iliazeus.vscode-ansi"
vscode "ipedrazas.kubernetes-snippets"
vscode "ironmansoftware.powershellprotools"
vscode "jfrog.jfrog-vscode-extension"
vscode "johnpapa.winteriscoming"
vscode "kaih2o.python-resource-monitor"
vscode "kargware.vscode-extension-jekyll-kw"
vscode "kennylong.kubernetes-yaml-formatter"
vscode "kevinrose.vsc-python-indent"
vscode "laszer25.terraform-azure-autocomplete"
vscode "littlefoxteam.vscode-python-test-adapter"
vscode "lunuan.kubernetes-templates"
vscode "mads-hartmann.bash-ide-vscode"
vscode "me-dutour-mathieu.vscode-github-actions"
vscode "mechatroner.rainbow-csv"
vscode "mgesbert.python-path"
vscode "mhutchie.git-graph"
vscode "mindaro-dev.file-downloader"
vscode "mindaro.mindaro"
vscode "mintlify.document"
vscode "ms-azure-devops.azure-pipelines"
vscode "ms-azuretools.azure-dev"
vscode "ms-azuretools.vscode-azureappservice"
vscode "ms-azuretools.vscode-azurecontainerapps"
vscode "ms-azuretools.vscode-azurefunctions"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-azurestaticwebapps"
vscode "ms-azuretools.vscode-azurestorage"
vscode "ms-azuretools.vscode-azureterraform"
vscode "ms-azuretools.vscode-azurevirtualmachines"
vscode "ms-azuretools.vscode-cosmosdb"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.kind-vscode"
vscode "ms-kubernetes-tools.vscode-aks-tools"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.azure-account"
vscode "ms-vscode.azurecli"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.powershell"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.test-adapter-converter"
vscode "ms-vscode.vscode-node-azure-pack"
vscode "nhoizey.gremlins"
vscode "njpwerner.autodocstring"
vscode "njqdev.vscode-python-typehint"
vscode "oderwat.indent-rainbow"
vscode "perkovec.emoji"
vscode "pjmiravalle.terraform-advanced-syntax-highlighting"
vscode "pkief.material-icon-theme"
vscode "poeticandroid.vscode-poetry"
vscode "premparihar.gotestexplorer"
vscode "quicktype.quicktype"
vscode "redhat.vscode-yaml"
vscode "rogalmic.bash-debug"
vscode "rohgarg.jekyll-post"
vscode "run-at-scale.terraform-doc-snippets"
vscode "sandipchitale.vscode-kubernetes-helm-extras"
vscode "seltonfiuza.terragrunt-easy-plan"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "sourcery.sourcery"
vscode "starkwang.markdown"
vscode "streetsidesoftware.code-spell-checker"
vscode "technosophos.vscode-helm"
vscode "teticio.python-envy"
vscode "thebarkman.vscode-djaneiro"
vscode "tim-koehler.helm-intellisense"
vscode "timonwong.shellcheck"
vscode "trabpukcip.wolf"
vscode "tushortz.python-extended-snippets"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "waderyan.gitblame"
vscode "weaveworks.vscode-gitops-tools"
vscode "wholroyd.jinja"
vscode "xirider.livecode"
vscode "xrc-inc.jsonnet-formatter"
vscode "yesoreyeram.grafana"
vscode "yzane.markdown-pdf"
vscode "yzhang.markdown-all-in-one"
vscode "zainchen.json"
vscode "zeshuaro.vscode-python-poetry"
vscode "zhang-renyang.chat-gpt"
vscode "ziyasal.vscode-open-in-github"
vscode "zxh404.vscode-proto3"
