# core/import.sh — detect installed tools and merge into inventory (never uninstalls).
# shellcheck shell=bash
# Expects: DOTFILES, log_*, MACCTL_DRY_RUN, MACCTL_IMPORT_FORCE, MACCTL_ONLY (optional).

import_tolower() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }

import_ecosystem_selected() {
  local name="$1"
  [[ -z "${MACCTL_ONLY:-}" ]] && return 0
  case ",$(import_tolower "${MACCTL_ONLY}")," in
    *",${name},"*) return 0 ;;
    *) return 1 ;;
  esac
}

# Timestamped directory under state/import-backups/<ts>/ mirroring repo-relative paths.
import_prepare_backup_root() {
  IMPORT_BACKUP_ROOT="${DOTFILES}/state/import-backups/$(date -u +%Y%m%dT%H%M%SZ)"
  mkdir -p "$IMPORT_BACKUP_ROOT"
}

import_backup_path() {
  local f="$1"
  local rel="${f#"${DOTFILES}"/}"
  echo "${IMPORT_BACKUP_ROOT}/${rel}"
}

import_backup_file() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  local dst
  dst="$(import_backup_path "$f")"
  mkdir -p "$(dirname "$dst")"
  cp -p "$f" "$dst"
  log_info "import: backed up → ${dst#"${DOTFILES}"/}"
}

# Merge: keep leading # and blank lines from original, then sorted unique non-comment body lines.
# $1 = path, $2 = temp file with new lines (one per line, no comments).
import_merge_list_file() {
  local target="$1" new_lines="$2"
  local hdr body out merged lastc
  hdr=$(mktemp)
  body=$(mktemp)
  out=$(mktemp)
  merged=$(mktemp)
  if [[ -f "$target" ]]; then
    local mode=header
    while IFS= read -r line || [[ -n "$line" ]]; do
      if [[ "$mode" == header ]] && { [[ -z "${line//[[:space:]]/}" ]] || [[ "$line" =~ ^[[:space:]]*# ]]; }; then
        printf '%s\n' "$line" >>"$hdr"
      elif [[ "$mode" == header ]] && [[ -n "${line//[[:space:]]/}" ]]; then
        mode=body
        printf '%s\n' "$line" >>"$body"
      else
        printf '%s\n' "$line" >>"$body"
      fi
    done <"$target"
  else
    printf '# Generated by macctl import\n' >"$hdr"
    : >"$body"
  fi
  {
    cat "$body"
    cat "$new_lines"
  } | sed '/^[[:space:]]*$/d; /^[[:space:]]*#/d' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | grep -v '^$' | sort -u >"$out"
  {
    cat "$hdr"
    if [[ -s "$hdr" ]]; then
      lastc="$(tail -c1 "$hdr" 2>/dev/null || printf '')"
      [[ "$lastc" != $'\n' ]] && printf '\n'
    fi
    cat "$out"
  } >"$merged"
  mv "$merged" "$target"
  rm -f "$hdr" "$body" "$out"
}

import_write_list() {
  local target="$1" new_lines="$2"
  local mode="merge"
  [[ "${MACCTL_IMPORT_FORCE:-0}" -eq 1 ]] && mode="replace"
  if [[ "${MACCTL_DRY_RUN:-0}" -eq 1 ]]; then
    log_info "import: DRY-RUN would update ${target#"${DOTFILES}"/} (${mode})"
    return 0
  fi
  import_backup_file "$target"
  mkdir -p "$(dirname "$target")"
  if [[ "$mode" == replace ]]; then
    {
      printf '# Regenerated by macctl import (force). Review before commit.\n'
      sed '/^[[:space:]]*$/d; /^[[:space:]]*#/d' "$new_lines" | sort -u
    } >"$target"
  elif [[ ! -f "$target" ]]; then
    {
      printf '# Generated by macctl import\n'
      sort -u "$new_lines"
    } >"$target"
  else
    cp "$target" "${target}.preimport"
    import_merge_list_file "$target" "$new_lines"
    rm -f "${target}.preimport"
  fi
}

# --- Brew: parse Brewfile tokens (duplicate brew.sh patterns; avoids sourcing register_module) ---
import_brew__parse_formulae() {
  local bf="$1"
  [[ -f "$bf" ]] || return 0
  grep -E '^[[:space:]]*brew[[:space:]]+"' "$bf" 2>/dev/null | sed 's/#.*//' | sed -E 's/^[[:space:]]*brew[[:space:]]+"([^"]+)".*/\1/' | grep -v '^$' || true
}

import_brew__parse_taps() {
  local bf="$1"
  [[ -f "$bf" ]] || return 0
  grep -E '^[[:space:]]*tap[[:space:]]+"' "$bf" 2>/dev/null | sed 's/#.*//' | sed -E 's/^[[:space:]]*tap[[:space:]]+"([^"]+)".*/\1/' | grep -v '^$' || true
}

import_brew__parse_mas_ids() {
  local bf="$1"
  [[ -f "$bf" ]] || return 0
  grep -E '^[[:space:]]*mas[[:space:]]+"' "$bf" 2>/dev/null | sed -E 's/.*id:[[:space:]]*([0-9]+).*/\1/' | grep -E '^[0-9]+$' || true
}

import_brew__parse_vscode() {
  local bf="$1"
  [[ -f "$bf" ]] || return 0
  grep -E '^[[:space:]]*vscode[[:space:]]+"' "$bf" 2>/dev/null | sed 's/#.*//' | sed -E 's/^[[:space:]]*vscode[[:space:]]+"([^"]+)".*/\1/' | grep -v '^$' | tr '[:upper:]' '[:lower:]' || true
}

# True if Brewfile already references this formula name (short or full token).
import_brewfile_covers_formula() {
  local ins="$1" tok n
  ins="$(import_tolower "$ins")"
  while IFS= read -r tok; do
    [[ -z "$tok" ]] && continue
    n="$(import_tolower "${tok##*/}")"
    [[ "$n" == "$ins" ]] && return 0
    [[ "$(import_tolower "$tok")" == "$ins" ]] && return 0
  done <"$2"
  return 1
}

import_run_brew() {
  import_ecosystem_selected brew || return 0
  command -v brew &>/dev/null || {
    log_warn "import: brew not found; skipping Homebrew"
    return 0
  }
  local bf casks bf_new taps_have brew_have mas_have vs_have
  bf="${DOTFILES}/inventory/brew/Brewfile"
  casks="${DOTFILES}/inventory/brew/casks.txt"
  taps_have=$(mktemp)
  brew_have=$(mktemp)
  mas_have=$(mktemp)
  vs_have=$(mktemp)
  bf_new=$(mktemp)
  import_brew__parse_taps "$bf" | tr '[:upper:]' '[:lower:]' | sort -u >"$taps_have"
  import_brew__parse_formulae "$bf" | sort -u >"${brew_have}.full"
  import_brew__parse_mas_ids "$bf" | sort -u >"$mas_have"
  import_brew__parse_vscode "$bf" | sort -u >"$vs_have"

  local nf nc nt
  nf=0
  nc=0
  nt=0
  # Casks → casks.txt
  local ctmp
  ctmp=$(mktemp)
  brew list --cask -1 2>/dev/null | tr '[:upper:]' '[:lower:]' | sort -u >"$ctmp"
  nc=$(wc -l <"$ctmp" | tr -d ' ')
  import_write_list "$casks" "$ctmp"
  rm -f "$ctmp"

  # Brewfile: append missing taps, formulae, mas, vscode (never remove lines).
  {
    while IFS= read -r tap; do
      [[ -z "$tap" ]] && continue
      grep -Fxq "$(import_tolower "$tap")" "$taps_have" 2>/dev/null && continue
      printf 'tap "%s"\n' "$tap"
    done < <(brew tap 2>/dev/null | awk '{print $1}' | sort -u)

    local ftmp f
    ftmp=$(mktemp)
    brew list --formula -1 2>/dev/null | sort -u >"$ftmp"
    while IFS= read -r f; do
      [[ -z "$f" ]] && continue
      import_brewfile_covers_formula "$f" "${brew_have}.full" && continue
      printf 'brew "%s"\n' "$f"
      nf=$((nf + 1))
    done <"$ftmp"
    rm -f "$ftmp"

    if command -v mas &>/dev/null; then
      local id name line
      while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        id="${line%%[[:space:]]*}"
        [[ "$id" =~ ^[0-9]+$ ]] || continue
        grep -Fxq "$id" "$mas_have" 2>/dev/null && continue
        name="${line#*[[:space:]]}"
        name="${name%%[[:space:]]*\(*}"
        name="${name%"${name##*[![:space:]]}"}"
        [[ -z "$name" ]] && name="App ${id}"
        printf 'mas "%s", id: %s\n' "${name//\"/\\\"}" "$id"
        nt=$((nt + 1))
      done < <(mas list 2>/dev/null || true)
    fi

    if command -v code &>/dev/null; then
      local ext
      while IFS= read -r ext; do
        [[ -z "$ext" ]] && continue
        ext="$(import_tolower "$ext")"
        grep -Fxq "$ext" "$vs_have" 2>/dev/null && continue
        printf 'vscode "%s"\n' "$ext"
        nt=$((nt + 1))
      done < <(code --list-extensions 2>/dev/null | tr '[:upper:]' '[:lower:]' || true)
    fi
  } >"$bf_new"

  if [[ -s "$bf_new" ]]; then
    if [[ "${MACCTL_DRY_RUN:-0}" -eq 1 ]]; then
      log_info "import: DRY-RUN would append to Brewfile ($(wc -l <"$bf_new" | tr -d ' ') lines; new brew lines ≈ ${nf})"
    else
      import_backup_file "$bf"
      {
        printf '\n# --- macctl import %s ---\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        cat "$bf_new"
      } >>"$bf"
      log_info "import: appended $(wc -l <"$bf_new" | tr -d ' ') lines to inventory/brew/Brewfile"
    fi
  else
    log_info "import: Brewfile — no new taps/formulae/mas/vscode beyond existing inventory"
  fi
  rm -f "$bf_new" "$taps_have" "${brew_have}.full" "$mas_have" "$vs_have"
  log_info "import: Homebrew — ${nc} cask(s) on system; new brew declarations counted: ${nf}"
}

import_python_base() {
  local spec="$1"
  spec="${spec%%#*}"
  spec="${spec#"${spec%%[![:space:]]*}"}"
  spec="${spec%"${spec##*[![:space:]]}"}"
  [[ -z "$spec" ]] && return 1
  spec="${spec%%[*}"
  echo "$spec" | sed -E 's/^([a-zA-Z0-9_.+-]+).*/\1/' | tr '[:upper:]' '[:lower:]'
}

import_pip_skip() {
  case "$(import_tolower "$1")" in
    pip | setuptools | wheel | pipx | pkg_resources | packaging | distribute | distlib | setuptools-scm | virtualenv) return 0 ;;
    *) return 1 ;;
  esac
}

import_run_python() {
  import_ecosystem_selected python || return 0
  command -v python3 &>/dev/null || {
    log_warn "import: python3 not found; skipping Python"
    return 0
  }
  python3 -m pip --version &>/dev/null || {
    log_warn "import: pip not available; skipping Python"
    return 0
  }
  local req freeze merged n
  req="${DOTFILES}/inventory/python/requirements.txt"
  freeze=$(mktemp)
  merged=$(mktemp)
  python3 -m pip freeze 2>/dev/null | sort -u >"$freeze" || true
  n=0
  : >"$merged"
  local line spec base have
  have=$(mktemp)
  if [[ -f "$req" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
      line="${line//$'\r'/}"
      [[ -z "${line//[[:space:]]/}" || "$line" =~ ^[[:space:]]*# ]] && continue
      spec="${line#"${line%%[![:space:]]*}"}"
      spec="${spec%"${spec##*[![:space:]]}"}"
      [[ "$spec" =~ ^git\+|^https?:// ]] && continue
      base="$(import_python_base "$spec")" || continue
      echo "$base" >>"$have"
      printf '%s\n' "$line" >>"$merged"
    done <"$req"
  fi
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" ]] && continue
    base="$(import_python_base "$line")" || continue
    import_pip_skip "$base" && continue
    if grep -Fxq "$base" "$have" 2>/dev/null; then
      continue
    fi
    printf '%s\n' "$line" >>"$merged"
    n=$((n + 1))
  done <"$freeze"
  sort -u "$merged" -o "$merged.sorted"
  mv "$merged.sorted" "$merged"
  if [[ "${MACCTL_DRY_RUN:-0}" -eq 1 ]]; then
    log_info "import: DRY-RUN would write requirements.txt (+${n} new from freeze)"
    rm -f "$freeze" "$merged" "$have"
    return 0
  fi
  import_backup_file "$req"
  mkdir -p "$(dirname "$req")"
  {
    printf '# Declarative Python packages (macctl module python).\n'
    printf '# Merged by macctl import - pinned lines preserved where possible.\n'
    grep -v '^[[:space:]]*#' "$merged" | grep -v '^[[:space:]]*$' | sort -u
  } >"$req"
  rm -f "$freeze" "$merged" "$have"
  log_info "import: Python — merged requirements.txt (new lines from freeze: ${n})"
}

import_run_node() {
  import_ecosystem_selected node || return 0
  command -v npm &>/dev/null || {
    log_warn "import: npm not found; skipping Node"
    return 0
  }
  local inv tmp n
  inv="${DOTFILES}/inventory/node/global-packages.txt"
  tmp=$(mktemp)
  : >"$tmp"
  if command -v node &>/dev/null; then
    node -e '
      try {
        const { execSync } = require("child_process");
        const o = execSync("npm ls -g --depth=0 --json", { encoding: "utf8" });
        const j = JSON.parse(o);
        const d = j.dependencies || {};
        const skip = new Set(["npm", "corepack"]);
        for (const k of Object.keys(d)) {
          if (!skip.has(k)) process.stdout.write(k + "\n");
        }
      } catch (e) { process.exit(0); }
    ' 2>/dev/null >>"$tmp" || true
  fi
  n=$(wc -l <"$tmp" | tr -d ' ')
  [[ -z "$n" ]] && n=0
  import_write_list "$inv" "$tmp"
  rm -f "$tmp"
  log_info "import: Node — detected ${n} global package(s) → inventory/node/global-packages.txt"
}

import_golang_match() {
  local f="$1"
  f="$(import_tolower "$f")"
  case "$f" in
    go | golang | golang-migrate | goreleaser | mockery | gotestsum | delve | staticcheck) return 0 ;;
  esac
  [[ "$f" == go-* ]] && return 0
  [[ "$f" == golang-* ]] && return 0
  return 1
}

import_run_golang() {
  import_ecosystem_selected golang || return 0
  command -v brew &>/dev/null || return 0
  local inv tmp n
  inv="${DOTFILES}/inventory/golang/formulae.txt"
  tmp=$(mktemp)
  : >"$tmp"
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    import_golang_match "$f" && printf '%s\n' "$f" >>"$tmp"
  done < <(brew list --formula -1 2>/dev/null || true)
  n=$(wc -l <"$tmp" | tr -d ' ')
  [[ -z "$n" ]] && n=0
  import_write_list "$inv" "$tmp"
  rm -f "$tmp"
  log_info "import: Golang — ${n} matching brew formula(e) → inventory/golang/formulae.txt"
}

import_run_vim() {
  import_ecosystem_selected vim || return 0
  local out tmp n
  out="${DOTFILES}/inventory/vim/plugins.txt"
  tmp=$(mktemp)
  : >"$tmp"
  local rc
  for rc in "$HOME/.vimrc" "$HOME/.config/nvim/init.vim" "$HOME/.config/nvim/init.lua"; do
    [[ -f "$rc" ]] || continue
    grep -hE '^[[:space:]]*Plug[[:space:]]+' "$rc" 2>/dev/null \
      | sed -E "s/^[[:space:]]*Plug[[:space:]]+['\"]([^'\"]+)['\"].*/\1/" \
      | grep -v '^$' >>"$tmp" || true
  done
  sort -u "$tmp" -o "$tmp"
  n=$(wc -l <"$tmp" | tr -d ' ')
  [[ -z "$n" || "$n" == 0 ]] && n=0
  if [[ "$n" -eq 0 ]]; then
    log_info "import: Vim — no Plug lines found in ~/.vimrc / nvim init"
    rm -f "$tmp"
    return 0
  fi
  if [[ "${MACCTL_DRY_RUN:-0}" -eq 1 ]]; then
    log_info "import: DRY-RUN would write inventory/vim/plugins.txt (${n} repos)"
    rm -f "$tmp"
    return 0
  fi
  import_backup_file "$out"
  mkdir -p "$(dirname "$out")"
  {
    printf '# vim-plug repositories (owner/repo), detected from ~/.vimrc or nvim init.\n'
    printf '# Not consumed by macctl apply yet — copy into your vimrc or extend the vim module.\n'
    cat "$tmp"
  } >"$out"
  rm -f "$tmp"
  log_info "import: Vim — wrote ${n} plugin repos → inventory/vim/plugins.txt"
}

import_ia_known_formulae() {
  printf '%s\n' ollama bun k9s stern kubectl helm terraform opentofu azure-cli gh k6 trivy kind minikube kustomize
}

import_run_ia() {
  import_ecosystem_selected ia || return 0
  local man uv tmp n mtmp
  man="${DOTFILES}/inventory/ia/manifest.txt"
  uv="${DOTFILES}/inventory/ia/uv-packages.txt"
  mtmp=$(mktemp)
  if [[ -f "$man" ]]; then
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      echo "$(import_tolower "$line")"
    done < <(grep -E '^(brew_formula|brew_cask|tap):' "$man" 2>/dev/null || true) | sort -u >"$mtmp"
  else
    : >"$mtmp"
  fi
  n=0
  local manifest_backed=0
  if command -v brew &>/dev/null; then
    local f line
    while IFS= read -r f; do
      [[ -z "$f" ]] && continue
      brew list --formula -1 2>/dev/null | grep -Fxq "$f" || continue
      line="brew_formula:${f}"
      grep -Fxq "$(import_tolower "$line")" "$mtmp" 2>/dev/null && continue
      if [[ "${MACCTL_DRY_RUN:-0}" -eq 1 ]]; then
        log_info "import: DRY-RUN would append to manifest: ${line}"
        n=$((n + 1))
        continue
      fi
      if [[ "$manifest_backed" -eq 0 ]]; then
        import_backup_file "$man"
        manifest_backed=1
      fi
      mkdir -p "$(dirname "$man")"
      [[ -f "$man" ]] || printf '# IA manifest (macctl module ia)\n' >"$man"
      printf '%s\n' "$line" >>"$man"
      echo "$(import_tolower "$line")" >>"$mtmp"
      n=$((n + 1))
    done < <(import_ia_known_formulae)
  fi
  log_info "import: IA manifest — would append / appended ${n} brew_formula line(s) for known tools on system"

  tmp=$(mktemp)
  : >"$tmp"
  if command -v uv &>/dev/null; then
    uv pip freeze 2>/dev/null | cut -d= -f1 | tr '[:upper:]' '[:lower:]' | sort -u >"$tmp" || true
  fi
  local nu
  nu=$(wc -l <"$tmp" | tr -d ' ')
  import_write_list "$uv" "$tmp"
  rm -f "$tmp" "$mtmp"
  log_info "import: IA uv-packages — merged ${nu} package name(s) from uv pip (if uv available)"
}

run_import() {
  log_info "import: starting (dry-run=${MACCTL_DRY_RUN:-0} force=${MACCTL_IMPORT_FORCE:-0} only='${MACCTL_ONLY:-}')"
  [[ -d "$DOTFILES" ]] || {
    log_error "import: DOTFILES is not a directory"
    return 1
  }
  if [[ "${MACCTL_DRY_RUN:-0}" -ne 1 ]]; then
    import_prepare_backup_root
    log_info "import: backup root ${IMPORT_BACKUP_ROOT#"${DOTFILES}"/}"
  fi

  import_run_brew
  import_run_python
  import_run_node
  import_run_golang
  import_run_vim
  import_run_ia

  log_info "import: finished (nothing was removed or uninstalled)"
}
